name: flowbite_icons
description: Collection of beautiful and well-designed icons from Flowbite UI Kit
version: 0.0.3
homepage: https://github.com/hanmajid/flowbite_icons
issue_tracker: https://github.com/hanmajid/flowbite_icons/issues
repository: https://github.com/hanmajid/flowbite_icons
funding:
  - https://github.com/sponsors/hanmajid

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.5'

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: FlowbiteOutlineIcons
      fonts:
        - asset: assets/FlowbiteOutlineIcons.ttf
    - family: FlowbiteSocialIcons
      fonts:
        - asset: assets/FlowbiteSocialIcons.ttf
    - family: FlowbiteSolidIcons
      fonts:
        - asset: assets/FlowbiteSolidIcons.ttf

topics:
  - assets
  - icons
  - ui

screenshots:
  - description: 'Flowbite icons'
    path: flowbite-icons.png