// Copyright 2023 hanmajid (Muhammad Farhan Majid)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import 'package:flutter/widgets.dart';

/// Class containing Flowbite solid icons.
///
/// This font was generated by FlutterIcon.com.
class FlowbiteSolidIcons {
  /// No need for constructor. All properties are static.
  FlowbiteSolidIcons._();

  /// Flowbite solid icons family name.
  static const _kFontFam = 'FlowbiteSolidIcons';

  /// Flowbite icons package name.
  static const String? _kFontPkg = 'flowbite_icons';

  /// Icon data for solid 'add_user' glyph.
  static const IconData add_user =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'adjustments_horizontal' glyph.
  static const IconData adjustments_horizontal =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'adjustments_vertical' glyph.
  static const IconData adjustments_vertical =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'adress_book' glyph.
  static const IconData adress_book =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'align_center' glyph.
  static const IconData align_center =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'angle_right' glyph.
  static const IconData angle_right =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'arrow_down_to_bracket' glyph.
  static const IconData arrow_down_to_bracket =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'annotation' glyph.
  static const IconData annotation =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'angle_down' glyph.
  static const IconData angle_down =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'arrow_left_to_bracket' glyph.
  static const IconData arrow_left_to_bracket =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'angle_left' glyph.
  static const IconData angle_left =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'arrow_right_arrow_left' glyph.
  static const IconData arrow_right_arrow_left =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'arrow_down' glyph.
  static const IconData arrow_down =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'arrow_right' glyph.
  static const IconData arrow_right =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'archive' glyph.
  static const IconData archive =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'angle_up' glyph.
  static const IconData angle_up =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'arrow_sort' glyph.
  static const IconData arrow_sort =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'arrow_sort_letters' glyph.
  static const IconData arrow_sort_letters =
      IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'arrow_up_right_from_square' glyph.
  static const IconData arrow_up_right_from_square =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'arrow_right_to_bracket' glyph.
  static const IconData arrow_right_to_bracket =
      IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'arrows_repeat_1' glyph.
  static const IconData arrows_repeat_1 =
      IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'bell_active_alt' glyph.
  static const IconData bell_active_alt =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'bell_active' glyph.
  static const IconData bell_active =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'bell_on' glyph.
  static const IconData bell_on =
      IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'badge_check' glyph.
  static const IconData badge_check =
      IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'book' glyph.
  static const IconData book =
      IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'bookmark' glyph.
  static const IconData bookmark =
      IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'brain' glyph.
  static const IconData brain =
      IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'briefcase' glyph.
  static const IconData briefcase =
      IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'atom' glyph.
  static const IconData atom =
      IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'bug' glyph.
  static const IconData bug =
      IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'arrow_left' glyph.
  static const IconData arrow_left =
      IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'bullhorn' glyph.
  static const IconData bullhorn =
      IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'arrow_up' glyph.
  static const IconData arrow_up =
      IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'blender_phone' glyph.
  static const IconData blender_phone =
      IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'calendar_edit' glyph.
  static const IconData calendar_edit =
      IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'bell' glyph.
  static const IconData bell =
      IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'calendar_day' glyph.
  static const IconData calendar_day =
      IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'camera_foto' glyph.
  static const IconData camera_foto =
      IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'bars' glyph.
  static const IconData bars =
      IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'arrows_repeat' glyph.
  static const IconData arrows_repeat =
      IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'calendar_month' glyph.
  static const IconData calendar_month =
      IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'backward_step' glyph.
  static const IconData backward_step =
      IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'captioning' glyph.
  static const IconData captioning =
      IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'cart' glyph.
  static const IconData cart =
      IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'cart_plus' glyph.
  static const IconData cart_plus =
      IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'caret_left' glyph.
  static const IconData caret_left =
      IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'caret_sort' glyph.
  static const IconData caret_sort =
      IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'caret_right' glyph.
  static const IconData caret_right =
      IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'cash' glyph.
  static const IconData cash =
      IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'caret_down' glyph.
  static const IconData caret_down =
      IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'bag' glyph.
  static const IconData bag =
      IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'chart_line_up' glyph.
  static const IconData chart_line_up =
      IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'caret_up' glyph.
  static const IconData caret_up =
      IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'cart_plus_alt' glyph.
  static const IconData cart_plus_alt =
      IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'check_circle' glyph.
  static const IconData check_circle =
      IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'check' glyph.
  static const IconData check =
      IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'chart_mixed' glyph.
  static const IconData chart_mixed =
      IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'chevron_left' glyph.
  static const IconData chevron_left =
      IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'chart_line_down' glyph.
  static const IconData chart_line_down =
      IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'chevron_down' glyph.
  static const IconData chevron_down =
      IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'chevron_double_up' glyph.
  static const IconData chevron_double_up =
      IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'chevron_double_down' glyph.
  static const IconData chevron_double_down =
      IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'chart_pie' glyph.
  static const IconData chart_pie =
      IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'chart' glyph.
  static const IconData chart =
      IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'chevron_double_right' glyph.
  static const IconData chevron_double_right =
      IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'chevron_right' glyph.
  static const IconData chevron_right =
      IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'chevron_sort' glyph.
  static const IconData chevron_sort =
      IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'chevron_double_left' glyph.
  static const IconData chevron_double_left =
      IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'chevron_up' glyph.
  static const IconData chevron_up =
      IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'clipboard_list' glyph.
  static const IconData clipboard_list =
      IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'clipboard_check' glyph.
  static const IconData clipboard_check =
      IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'clock' glyph.
  static const IconData clock =
      IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'clone' glyph.
  static const IconData clone =
      IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'code_merge' glyph.
  static const IconData code_merge =
      IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'code_branch' glyph.
  static const IconData code_branch =
      IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'copy' glyph.
  static const IconData copy =
      IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'code' glyph.
  static const IconData code =
      IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'computer_speaker' glyph.
  static const IconData computer_speaker =
      IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'credit_card' glyph.
  static const IconData credit_card =
      IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'code_pull_request' glyph.
  static const IconData code_pull_request =
      IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'database' glyph.
  static const IconData database =
      IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'desktop_pc' glyph.
  static const IconData desktop_pc =
      IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'compress' glyph.
  static const IconData compress =
      IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'dna' glyph.
  static const IconData dna =
      IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'clipboard' glyph.
  static const IconData clipboard =
      IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'code_fork' glyph.
  static const IconData code_fork =
      IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'clapperboard_play' glyph.
  static const IconData clapperboard_play =
      IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'dots_horizontal' glyph.
  static const IconData dots_horizontal =
      IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'draw_square' glyph.
  static const IconData draw_square =
      IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'cog' glyph.
  static const IconData cog =
      IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'download' glyph.
  static const IconData download =
      IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'dots_vertical' glyph.
  static const IconData dots_vertical =
      IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'cloud_arrow_up' glyph.
  static const IconData cloud_arrow_up =
      IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'edit' glyph.
  static const IconData edit =
      IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'euro' glyph.
  static const IconData euro =
      IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'edit_user' glyph.
  static const IconData edit_user =
      IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'envelope_open' glyph.
  static const IconData envelope_open =
      IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'envelope' glyph.
  static const IconData envelope =
      IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'dollar' glyph.
  static const IconData dollar =
      IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'exclamation' glyph.
  static const IconData exclamation =
      IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'expand' glyph.
  static const IconData expand =
      IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'eye_slash' glyph.
  static const IconData eye_slash =
      IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'eye' glyph.
  static const IconData eye =
      IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'face_explode' glyph.
  static const IconData face_explode =
      IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'face_grin_stars' glyph.
  static const IconData face_grin_stars =
      IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'face_grin' glyph.
  static const IconData face_grin =
      IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'face_laugh' glyph.
  static const IconData face_laugh =
      IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'file_chart_bar' glyph.
  static const IconData file_chart_bar =
      IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'file_check' glyph.
  static const IconData file_check =
      IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'file_circle_plus' glyph.
  static const IconData file_circle_plus =
      IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'file_code' glyph.
  static const IconData file_code =
      IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'file_copy' glyph.
  static const IconData file_copy =
      IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'file_csv' glyph.
  static const IconData file_csv =
      IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'file_export' glyph.
  static const IconData file_export =
      IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'file_image' glyph.
  static const IconData file_image =
      IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'file_import' glyph.
  static const IconData file_import =
      IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'file_lines' glyph.
  static const IconData file_lines =
      IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'file_music' glyph.
  static const IconData file_music =
      IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'file_pdf' glyph.
  static const IconData file_pdf =
      IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'file_pen' glyph.
  static const IconData file_pen =
      IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'file_ppt' glyph.
  static const IconData file_ppt =
      IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'file_shield' glyph.
  static const IconData file_shield =
      IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'file_video' glyph.
  static const IconData file_video =
      IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'file_word' glyph.
  static const IconData file_word =
      IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'file' glyph.
  static const IconData file =
      IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'filter' glyph.
  static const IconData filter =
      IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'fingerprint' glyph.
  static const IconData fingerprint =
      IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'fire' glyph.
  static const IconData fire =
      IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'folder_1' glyph.
  static const IconData folder_1 =
      IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'folder_plus_1' glyph.
  static const IconData folder_plus_1 =
      IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'folder_plus' glyph.
  static const IconData folder_plus =
      IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'folder' glyph.
  static const IconData folder =
      IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'forward_step' glyph.
  static const IconData forward_step =
      IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'forward' glyph.
  static const IconData forward =
      IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'gift' glyph.
  static const IconData gift =
      IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'globe' glyph.
  static const IconData globe =
      IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'grid_plus' glyph.
  static const IconData grid_plus =
      IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'grid' glyph.
  static const IconData grid =
      IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'headphones' glyph.
  static const IconData headphones =
      IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'heart' glyph.
  static const IconData heart =
      IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'home' glyph.
  static const IconData home =
      IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'hourglass' glyph.
  static const IconData hourglass =
      IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'image' glyph.
  static const IconData image =
      IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'inbox_full' glyph.
  static const IconData inbox_full =
      IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'inbox' glyph.
  static const IconData inbox =
      IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'info' glyph.
  static const IconData info =
      IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'italic' glyph.
  static const IconData italic =
      IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'keyboard' glyph.
  static const IconData keyboard =
      IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'layers' glyph.
  static const IconData layers =
      IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'letter_bold' glyph.
  static const IconData letter_bold =
      IconData(0xe896, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'life_buoy' glyph.
  static const IconData life_buoy =
      IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'link' glyph.
  static const IconData link =
      IconData(0xe898, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'list_music' glyph.
  static const IconData list_music =
      IconData(0xe899, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'list' glyph.
  static const IconData list =
      IconData(0xe89a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'lock_open' glyph.
  static const IconData lock_open =
      IconData(0xe89b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'lock' glyph.
  static const IconData lock =
      IconData(0xe89c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'mail_box' glyph.
  static const IconData mail_box =
      IconData(0xe89d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'map_pin_alt' glyph.
  static const IconData map_pin_alt =
      IconData(0xe89e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'map_pin' glyph.
  static const IconData map_pin =
      IconData(0xe89f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'maximize' glyph.
  static const IconData maximize =
      IconData(0xe8a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'message_caption' glyph.
  static const IconData message_caption =
      IconData(0xe8a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'message_dots' glyph.
  static const IconData message_dots =
      IconData(0xe8a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'messages' glyph.
  static const IconData messages =
      IconData(0xe8a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'microphone' glyph.
  static const IconData microphone =
      IconData(0xe8a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'minimize' glyph.
  static const IconData minimize =
      IconData(0xe8a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'moon' glyph.
  static const IconData moon =
      IconData(0xe8a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'newspapper' glyph.
  static const IconData newspapper =
      IconData(0xe8a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'open_book' glyph.
  static const IconData open_book =
      IconData(0xe8a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'ordored_list' glyph.
  static const IconData ordored_list =
      IconData(0xe8aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'palette' glyph.
  static const IconData palette =
      IconData(0xe8ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'paper_clip' glyph.
  static const IconData paper_clip =
      IconData(0xe8ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'papper_plane' glyph.
  static const IconData papper_plane =
      IconData(0xe8ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'paste' glyph.
  static const IconData paste =
      IconData(0xe8ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'pause' glyph.
  static const IconData pause =
      IconData(0xe8af, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'pen_nib' glyph.
  static const IconData pen_nib =
      IconData(0xe8b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'pen' glyph.
  static const IconData pen =
      IconData(0xe8b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'phone_1' glyph.
  static const IconData phone_1 =
      IconData(0xe8b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'phone' glyph.
  static const IconData phone =
      IconData(0xe8b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'pin' glyph.
  static const IconData pin =
      IconData(0xe8b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'play' glyph.
  static const IconData play =
      IconData(0xe8b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'printer' glyph.
  static const IconData printer =
      IconData(0xe8b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'profile_card' glyph.
  static const IconData profile_card =
      IconData(0xe8b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'question_mark' glyph.
  static const IconData question_mark =
      IconData(0xe8b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'quote' glyph.
  static const IconData quote =
      IconData(0xe8ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'receipt' glyph.
  static const IconData receipt =
      IconData(0xe8bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'rectangle_list' glyph.
  static const IconData rectangle_list =
      IconData(0xe8bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'remove_user' glyph.
  static const IconData remove_user =
      IconData(0xe8bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'reply_all' glyph.
  static const IconData reply_all =
      IconData(0xe8be, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'rocket' glyph.
  static const IconData rocket =
      IconData(0xe8bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'rotate' glyph.
  static const IconData rotate =
      IconData(0xe8c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'rule_combined' glyph.
  static const IconData rule_combined =
      IconData(0xe8c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'sale_percent' glyph.
  static const IconData sale_percent =
      IconData(0xe8c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'scale_balanced' glyph.
  static const IconData scale_balanced =
      IconData(0xe8c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'search' glyph.
  static const IconData search =
      IconData(0xe8c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'share_all' glyph.
  static const IconData share_all =
      IconData(0xe8c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'share_nodes' glyph.
  static const IconData share_nodes =
      IconData(0xe8c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'shield' glyph.
  static const IconData shield =
      IconData(0xe8c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'shuffle' glyph.
  static const IconData shuffle =
      IconData(0xe8c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'sort' glyph.
  static const IconData sort =
      IconData(0xe8c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'star_half_stroke' glyph.
  static const IconData star_half_stroke =
      IconData(0xe8ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'star_half' glyph.
  static const IconData star_half =
      IconData(0xe8cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'star' glyph.
  static const IconData star =
      IconData(0xe8cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'store' glyph.
  static const IconData store =
      IconData(0xe8cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'sun' glyph.
  static const IconData sun =
      IconData(0xe8ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'swatchbook' glyph.
  static const IconData swatchbook =
      IconData(0xe8cf, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'table_column' glyph.
  static const IconData table_column =
      IconData(0xe8d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'table_row' glyph.
  static const IconData table_row =
      IconData(0xe8d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'tablet' glyph.
  static const IconData tablet =
      IconData(0xe8d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'tag' glyph.
  static const IconData tag =
      IconData(0xe8d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'terminal' glyph.
  static const IconData terminal =
      IconData(0xe8d4, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'thumbs_down' glyph.
  static const IconData thumbs_down =
      IconData(0xe8d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'thumbs_up' glyph.
  static const IconData thumbs_up =
      IconData(0xe8d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'ticket' glyph.
  static const IconData ticket =
      IconData(0xe8d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'trash' glyph.
  static const IconData trash =
      IconData(0xe8d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'truck' glyph.
  static const IconData truck =
      IconData(0xe8d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'underline' glyph.
  static const IconData underline =
      IconData(0xe8da, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'upload' glyph.
  static const IconData upload =
      IconData(0xe8db, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'user_circle' glyph.
  static const IconData user_circle =
      IconData(0xe8dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'user_headset' glyph.
  static const IconData user_headset =
      IconData(0xe8dd, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'user_settings' glyph.
  static const IconData user_settings =
      IconData(0xe8de, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'user' glyph.
  static const IconData user =
      IconData(0xe8df, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'users_group' glyph.
  static const IconData users_group =
      IconData(0xe8e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'users' glyph.
  static const IconData users =
      IconData(0xe8e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'videocamera' glyph.
  static const IconData videocamera =
      IconData(0xe8e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'volume_down' glyph.
  static const IconData volume_down =
      IconData(0xe8e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'volume_up' glyph.
  static const IconData volume_up =
      IconData(0xe8e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'wallet' glyph.
  static const IconData wallet =
      IconData(0xe8e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'wand_magic_sparkles' glyph.
  static const IconData wand_magic_sparkles =
      IconData(0xe8e6, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'window_restore' glyph.
  static const IconData window_restore =
      IconData(0xe8e7, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'window' glyph.
  static const IconData window =
      IconData(0xe8e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'x_circle' glyph.
  static const IconData x_circle =
      IconData(0xe8e9, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'x' glyph.
  static const IconData x =
      IconData(0xe8ea, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'zip' glyph.
  static const IconData zip =
      IconData(0xe8eb, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'zoom_in' glyph.
  static const IconData zoom_in =
      IconData(0xe8ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'zoom_out' glyph.
  static const IconData zoom_out =
      IconData(0xe8ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'minus' glyph.
  static const IconData minus =
      IconData(0xe8ee, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for solid 'plus' glyph.
  static const IconData plus =
      IconData(0xe8ef, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
