// Copyright 2023 hanmajid (Muhammad Farhan Majid)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import 'package:flutter/widgets.dart';

/// Class containing Flowbite social icons.
///
/// This font was generated by FlutterIcon.com.
class FlowbiteSocialIcons {
  /// No need for constructor. All properties are static.
  FlowbiteSocialIcons._();

  /// Flowbite social icons family name.
  static const _kFontFam = 'FlowbiteSocialIcons';

  /// Flowbite icons package name.
  static const String? _kFontPkg = 'flowbite_icons';

  /// Icon data for 'discord' glyph.
  static const IconData discord =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'dribbble' glyph.
  static const IconData dribbble =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'dropbox' glyph.
  static const IconData dropbox =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'facebook' glyph.
  static const IconData facebook =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'github' glyph.
  static const IconData github =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'linkedin' glyph.
  static const IconData linkedin =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'stackoverflow' glyph.
  static const IconData stackoverflow =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'google' glyph.
  static const IconData google =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'twitter' glyph.
  static const IconData twitter =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'youtube' glyph.
  static const IconData youtube =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
